---
- hosts: localhost
  tasks:
    - debug:
        msg: "THIS IS YOUR MESSAGE: {{ message|default('THIS SPACE INTENTIONALLY LEFT BLANK') }}"
  become: no
- hosts: all:!windows
  roles:
    - common
